
extern zend_class_entry *phalcon2_encryption_security_uuid_timebaseduidinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon2_Encryption_Security_Uuid_TimeBasedUidInterface);

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon2_encryption_security_uuid_timebaseduidinterface_getdatetime, 0, 0, \\DateTimeImmutable, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon2_encryption_security_uuid_timebaseduidinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon2_Encryption_Security_Uuid_TimeBasedUidInterface, getDateTime, arginfo_phalcon2_encryption_security_uuid_timebaseduidinterface_getdatetime)
	PHP_FE_END
};
